version: '3.8'

services:
  app:
    image: openjdk:11
    # to build app.jar
    command: sh -c "./mvnw clean package -DskipTests"
    build:
      dockerfile: Dockerfile
      context: .
    container_name: qr-app
    volumes:
      - /tmp
    depends_on:
      - db
    restart: always
    ports:
      - '6060:6060'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/qrdb
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - app-network
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=qrdb
    ports:
      - '5432:5432'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
